### ISSUE TITLE
Implementation of chat rooms

### ISSUE THREAD

**Issue by yutomoriyasu** [yaggytter/POSSEscreen#12]
### Long initial loading

The app now retrieves all the messages from db when the page is being loaded. Because of that, it takes longer and longer time as the messages of db increases.

### Visibility of the messages of other sessions

Now we can see the messages from the previous session and we can't remove them from the page.

## How to solve these problems 

I suggested that the app should have some kind of chat rooms to separate each session. 

In order to implement this, the app should enable a user to make a chat room and generate a new URL that includes UUID of the chat room. 

Then the user shares the URL with the people who he or she wants to start another session together. 

When they access the URL, they can see the messages sent in the chat room. 

By implementing this, I think the two problems we have will be solved!

**Comment by yutomoriyasu** [comment]
@yaggytter 

## TODO

- [x] Make a chat-room-creating page
- [x] Implement generations of new URL
- [x] Make chat rooms according to the UUID of the URL  
- [ ] Implement client pages according to the roomId

**Comment by yutomoriyasu** [comment]
I will create a data model according to this document
https://firebase.google.com/docs/firestore/data-model?hl=ja#hierarchical-data
